### ISSUE TITLE
0.8 and 1.4 or 0.7 and 1.5

### ISSUE THREAD

**Issue by bermanjoe** [SeloSlav/FarmersFable#10]
I see that the previous issue on that is closed, but in the early charts we still use 0.8 and 1.4. Is it too time consuming to change that text and the charts to 0.7 and 1.5?

**Comment by SeloSlav** [comment]
Very easy to do. Just in the middle of uploading that change.

**Comment by SeloSlav** [comment]
Updated the graphics and some early text and charts to reflect this graph.
