### ISSUE TITLE
principle explanation - slides/text

### ISSUE THREAD

**Issue by Marcthewriter** [SeloSlav/FarmersFable#11]
I am fine with the current version, but I think it could be approved a bit. If it is doable within a justifiable amount of time.

![Bildschirmfoto 2019-05-03 um 18 35 53](https://user-images.githubusercontent.com/50121811/57152186-12a76c80-6dd3-11e9-8543-af8941cf8e08.png)

**Start like that.**
***
![Bildschirmfoto 2019-05-03 um 18 36 05](https://user-images.githubusercontent.com/50121811/57152187-12a76c80-6dd3-11e9-951c-a53d45ce5503.png)

**Just insert the sun and the first sentence.**

**New slide:
Insert the bundles and the second sentence.**
***
![Bildschirmfoto 2019-05-03 um 18 36 13](https://user-images.githubusercontent.com/50121811/57152189-12a76c80-6dd3-11e9-8f3a-cc85d5ef2a0d.png)

**Again: just insert the cloud and the first sentence.**

**New slide:
Insert the bundles and the second sentence.**
***
![Bildschirmfoto 2019-05-03 um 18 36 23](https://user-images.githubusercontent.com/50121811/57152190-12a76c80-6dd3-11e9-839e-bdd71884ccfc.png)

***
![Bildschirmfoto 2019-05-03 um 18 36 32](https://user-images.githubusercontent.com/50121811/57152191-12a76c80-6dd3-11e9-8a0e-1e5c9c437416.png)

***
![Bildschirmfoto 2019-05-03 um 18 36 43](https://user-images.githubusercontent.com/50121811/57152192-13400300-6dd3-11e9-8969-6bf12054f245.png)

***
![Bildschirmfoto 2019-05-03 um 18 36 54](https://user-images.githubusercontent.com/50121811/57152193-13400300-6dd3-11e9-8ec5-a7a5a0d81048.png)
***
![Bildschirmfoto 2019-05-03 um 18 37 06](https://user-images.githubusercontent.com/50121811/57152194-13400300-6dd3-11e9-9d95-b1681ebc1ca7.png)
***
![Bildschirmfoto 2019-05-03 um 18 37 15](https://user-images.githubusercontent.com/50121811/57152195-13d89980-6dd3-11e9-9e8e-57c55fcce37b.png)

**Delete this one**
***
![Bildschirmfoto 2019-05-03 um 18 37 23](https://user-images.githubusercontent.com/50121811/57152196-14713000-6dd3-11e9-9121-045fa4d33b16.png)

**Delete this one**
***
![Bildschirmfoto 2019-05-03 um 18 37 31](https://user-images.githubusercontent.com/50121811/57152197-14713000-6dd3-11e9-9593-ccc5ebfc1f25.png)

**Delete this one**
***
![Bildschirmfoto 2019-05-03 um 18 37 40](https://user-images.githubusercontent.com/50121811/57152198-14713000-6dd3-11e9-9d33-cc3843e1bcc6.png)
***
![Bildschirmfoto 2019-05-03 um 18 37 49](https://user-images.githubusercontent.com/50121811/57152199-14713000-6dd3-11e9-86f8-12520bf89900.png)

***
![Bildschirmfoto 2019-05-03 um 18 37 59](https://user-images.githubusercontent.com/50121811/57152200-1509c680-6dd3-11e9-9a50-70df7fa751ca.png)

**_text change:_ ... shared them equally, the following would happen:**
***
![Bildschirmfoto 2019-05-03 um 18 38 12](https://user-images.githubusercontent.com/50121811/57152202-1509c680-6dd3-11e9-966e-d0c523c655da.png)

**Delete this one**
***
![Bildschirmfoto 2019-05-03 um 18 38 19](https://user-images.githubusercontent.com/50121811/57152203-15a25d00-6dd3-11e9-955c-e8280f9f5082.png)

**Just insert cloud, not bundles**
***
![Bildschirmfoto 2019-05-03 um 18 38 29](https://user-images.githubusercontent.com/50121811/57152204-15a25d00-6dd3-11e9-815b-3bc5bb234993.png)

**insert bundles**
***
![Bildschirmfoto 2019-05-03 um 18 38 38](https://user-images.githubusercontent.com/50121811/57152205-15a25d00-6dd3-11e9-9a2d-7b0e1216a5e6.png)

**just insert sun, no bundles**
***
![Bildschirmfoto 2019-05-03 um 18 38 52](https://user-images.githubusercontent.com/50121811/57152206-163af380-6dd3-11e9-847b-a1d8e42a4a65.png)

**insert bundles**
***
![Bildschirmfoto 2019-05-03 um 18 39 00](https://user-images.githubusercontent.com/50121811/57152207-163af380-6dd3-11e9-8a65-1aa47a8d4b70.png)
***
![Bildschirmfoto 2019-05-03 um 18 39 08](https://user-images.githubusercontent.com/50121811/57152208-16d38a00-6dd3-11e9-87cc-94db86fa614d.png)
***
![Bildschirmfoto 2019-05-03 um 18 39 17](https://user-images.githubusercontent.com/50121811/57152209-16d38a00-6dd3-11e9-97bc-047d455f4e83.png)

**Do we need this last one?**

**Comment by Marcthewriter** [comment]
Have we decided yet whether we use 0.7 and 1.5 for this or go with full numbers for the growth factors?

Because if we use full numbers (and break the pattern with the rest of the story anyway) we should use x1 and x3 and start with just one bundle.

This would make everything much easier to grasp and oversee and the slide less cluttered then the current version.

It would lead to
 
Ann: 1 bundle > sun (x3) > 3 bundles > cloud (x1) > 3 bundles
Bill: 1 bundle > cloud (x1) > 1 bundle > sun (x3) > 3 bundles

And cooperation accordingly

first year pool Ann's 3 and Bill's 1 into 4, share into 2 each
second year pool Ann's (then) 2 and Bill's (then) 6, share into 4 each

What does everybody think?

**Comment by SeloSlav** [comment]
This slide in particular took about 8 hours. It's a lot more labor intensive than it looks.

If you guys can find a developer to do this at some point in the future then by all means please so, but I need to start putting hard caps on further development and this is one example where I just don't have time anymore.

I will provide full source code sometime next week to whoever needs it.

**Comment by SeloSlav** [comment]
I don't mean to sound terse, but we're two months over schedule and I don't normally directly work on coding projects. I just don't have the time so I'm pushing to wrap things up as best as possible.

I think the user gets the idea that if the multiplier is green then something positive has happened, and if the multiplier is red that something negative has happened...

So is there any way we can add text prior to the demonstration to just solidify this point further rather than update each slide (there are 23 in that section).

**Comment by Marcthewriter** [comment]
> This slide in particular took about 8 hours. It's a lot more labor intensive than it looks.
> 

Ah, I didn't know that. No problem. Then we'll have it as it is now with x1 and x2 and starting with 4 bushles :-)

> So if is there any way we can add text prior to the demonstration to just solidify this point further rather than update each slide (there are 23 in that section), perhaps that would be better?
> 

You can delete some of the slides (see long posting with pictures above) if that makes things easier.

And I'll think about text (and whether it is necessary).

**Comment by SeloSlav** [comment]
Thanks. Talk soon!

**Comment by SeloSlav** [comment]
I'm closing this one for now because the changes will take too long.
