### ISSUE TITLE
Long trajectory text

### ISSUE THREAD

**Issue by bermanjoe** [SeloSlav/FarmersFable#13]
I think that because the long trajectory takes some time, some of the users will not reach the point where the text changes to "this is amazing...".

Could we make sure that everyone sees it?

**Comment by SeloSlav** [comment]
Could we set it so the user cannot skip until the max value on x axis has elapsed? 

We could even warn the user earlier, saying "let's try this for 500 harvests"...

**Comment by bermanjoe** [comment]
I think it is better to make the calculation faster than not allowing skipping. Is that possible?

**Comment by SeloSlav** [comment]
Have exhausted every option currently. Unable to skip x values to simulate
faster trajectories. Looks like 500-1000 ticks is kind of the max we can do
without the user losing attention.

**Comment by bermanjoe** [comment]
OK. I guess we should leave it as it is then

**Comment by bermanjoe** [comment]
OK. I guess we should leave it as it is then
