### ISSUE TITLE
Shorten text

### ISSUE THREAD

**Issue by ole-peters** [SeloSlav/FarmersFable#14]
0 Start - ok

1 - ok

2 - ok

3 - ok

4 - ok

5 - change: can we delete the "[CLICK to learn more about the Wheat and chess board problem]"?
I think we can just make the "King's chessboard" text above into a link. This will save a lot of text on the page.

6 - ok

7 - shorten "To see this, we need to introduce bad seasons."

8 - ok

9 - ok

10 - delete this slide. This is a legacy slide from the previous story "As we can see Bill..."

11 - change: "Ann is also a farmer. She too faces good and bad seasons."

12 - change: "Ann's seasons obey the same statistics as Bill's but they are otherwise unrelated."

13 - change: "Now imagine that Bill and Ann make a pact. At the end of every season they pool their harvests and share them evenly."
This gets us away from any political opinions about marriage etc.

14 - ok

15 - change: "Let's compare to see how they would have done had they not pooled and shared their harvests."
(correction of past tense to past perfect) 
Delete "But is this a systematic effect or just luck?"

16 - change: "But is this a systematic effect or just luck? All trajectories are random, so in a sense it's always luck. But luck becomes certainty in the long run." 

16 b) change: "Pooling and sharing not only reduces risk. It increases growth for everybody involved."
No need to have Bill say this. Let's make it our observation, not his.

17 - change: "Anything that grows... fluctuations" is fine.
	Delete "Continue to learn...growth"
The computation is no longer optional, so we don't need to say "Continue to learn more" -- there's no other option here.

18* NEW SLIDE: include a slide with just Bill and Ann that says
	"Let's go through an example computation of how this works."

18 - there is too much text here that suggests many things other than the simple mathematics of the situation. Let's keep this as simple as possible

Ann starts with 4 bundles of wheat.
In the first harvest she doubles her wheat.
In the second harvest she only breaks even.

Bill also starts with 4 bundles.
In the first harvest he breaks even.
In the second harvest he doubles his wheat.

Both started with 4 bundles, and each ended up with 8.

Now imagine they had pooled and shared.
After the first harvest, Ann has 8 and Bill has 4.
The pool
and share
and both have 6

In the second harvest Ann again breaks even, to keep her 6.
Bill again doubles his wheat to 12.

They pool again
and share again
To end up with 9 bundles each -- one more each than without pooling and sharing.

Add one more slide (graphics can stay fixed) with a link to the paper that specifically discusses the cooperation benefit. At the moment we only link to the lecture notes, but that's too much for someone just interested in cooperation.
Text: "The full theory behind the cooperation benefit is worked out here"
where "here" links to https://www.researchers.one/article/2019-03-4

19 change "This insight..."
to "This insight is not present in modern economic theory, which therefore underestimates the benefits of cooperation. When the foundations of formal economics were laid in the 18th century, crucial mathematical insights were still lacking.

For our redevelopment of economic theory, please visit https://ergodicityeconomics.com/lecture-notes"

[make the text the link, maybe color/italicize/boldface it. Better thant "by [CLICKING HERE]"

20 - ok

21 - my slight preference is to just say "Science: London Mathematical Laboratory", and then leave the specific names to the next slide. Just because it looks better on the page.

22 - Questions
1 have you tried it without the twitter icons, and just the twitter handles? All those birds are filling up the page.
2 should we add Ryan who made the music? Just if you think it's fun.

**Comment by Marcthewriter** [comment]
sounds good

**Comment by ole-peters** [comment]
Maybe underline links? I think that's suggestive of the right thing.

Looks good, let me know when it's all done.

**Comment by SeloSlav** [comment]
I updated the external hyperlinks with blue underlines.

**Comment by ole-peters** [comment]
blue underlines are clear. To me that definitely suggests a link. They are the only color - do we want them colored? Is black better, i.e. more consistent?

I noticed that when I click a link, the music stops. Is that a setting we can change?

**Comment by SeloSlav** [comment]
For me, the music only stops momentarily when I click a link, then resumes. I won't be able to resolve this.

There is a separate bug where it turns off entirely when you click on one of the menu items to the right and turns on again when you click on one again. I think this bug was introduced recently. I'll look into.

As for the links. Let's go for black.

Can I close this issue now?

**Comment by ole-peters** [comment]
I agree, black may be better. If you think that looks ok, let's do that. 

Before you close the issue, do one page-by-page run-through with the list at hand. We still have the "As we can see, Bill faces..." slide in there, which we wanted to delete. 

Also some superfluous slides in the detailed computation, e.g. "Ann wasted less investment..." and "...and could profit from better..."

**Comment by Marcthewriter** [comment]
Black is better.

I'd have two more small issues: one I realized translating to German, the other durig several discussions and presentations with selected people during the past days.

1.
I also mention it in the translations to German - the slides withe the graphs of Ann and Bill:
SInce Ann (and Ann's Yield below) stands on the left side of the slide, the names in the captions should be placed accordingly - left Ann, right Bill. 

2. 
After introducing bad seasons, the slide with the graph: 
Now what happens? Let's try 100 harvests. /
Should we add here something like "For this simulation we use a random generator."?

People keep asking how those growth rates are generated.

**Comment by ole-peters** [comment]
1. sounds fine.
2. is a potential rabbit hole. What should the exact text be?
"Now what happens? Let's try 100 randomly generated harvests."
Is that better?

**Comment by ole-peters** [comment]
"... Let's say good and bad seasons are equally common and unpredictable."

Maybe we shouldn't say "Let's say" but rather just state the facts:
"Good and bad seasons are equally common and unpredictable."

**Comment by ole-peters** [comment]
That's actually quite neat - what more could we say?

They're equally common means 50/50 good and bad. Unpredictable means they're random.

Probably hundreds of thousands of pages have been written about what "random" means -- so that's the rabbit hole to avoid.

**Comment by ole-peters** [comment]
Maybe it's ok, with the "randomly generated" on the next slide? What do you think, Marc?

**Comment by Marcthewriter** [comment]
> "Good and bad seasons are equally common and unpredictable."
>
> Maybe it's ok, with the "randomly generated" on the next slide? What do you think, Marc?
>
Sounds good

**Comment by ole-peters** [comment]
Ok, so we have
1 "In a bad season, Bill only harvests 70 seeds for each 100 he sows. Good and bad seasons are equally common and unpredictable."
2 "Now what happens? Let's try 100 randomly generated harvests."

**Comment by Marcthewriter** [comment]
Sounds good to me

**Comment by ole-peters** [comment]
See first comment here:

Slide 10 still needs to be deleted, unless that's a conscious decision not to. I think it can go.

Also, in slide 18 (the computation) there are still suggestive slides that should go (see first comment). The suggestive slides are
"So Ann wasted less investment on bad growth"
and 
"And could profit from better pre-conditions"

Both are true, of course, but don't provide the explanation for what's happening. They actually sound as if Ann knew that growth would be bad, so she invested less, and similar for Bill.

**Comment by SeloSlav** [comment]
Should be fixed now.
