### ISSUE TITLE
One introductory slide

### ISSUE THREAD

**Issue by davidsarac** [SeloSlav/FarmersFable#16]
My only comment is that the story starts a bit abruptly. 

Can we have at least one slide (before first slide "This is farmer Bill" - even if it is only text/introduction? Just a paragraph or two to ease a person into the story?

**Comment by SeloSlav** [comment]
Here is Nicky Case's introductory text. One short slide. I like how it provides context for why it is so that important we know what game theory is.

![image](https://user-images.githubusercontent.com/8828948/57483250-4236f880-725b-11e9-8e61-50b5561b0682.png)

**Comment by Marcthewriter** [comment]
Do we need an entire slide?
(Considering out time issue)

Or might it be enough to play around with the title a bit?

(Actually, should it be Farmer's Fable or Farmers' Fable or Farmers Fable?)

Farmer's fable
The secret of cooperation

Farmer's fable
The secret benefit of cooperation

Farmer's fable
The unknown benefit of cooperation

Farmer's fable
Shifting paradigm: The unknown benefit of cooperation

Suggestions?

**Comment by Marcthewriter** [comment]
And hereby I am finished since Martin wants to close the issues

**Comment by SeloSlav** [comment]
Implementing this would take less than 5 minutes with text provided so on the margin it seems like a high value add. I also agree that it jumps too suddenly in to the story. What do others think? I believe @ole-peters wrote some kind of introduction in one of the documents that could fit well. Marc, what do you think?

**Comment by Marcthewriter** [comment]
I'd be okay with it. Hadn't the chance to think too much about it. Do you remember in which context @ole-peters wrote some?

**Comment by Marcthewriter** [comment]
Any idea about an approach to the intro?

**Comment by Marcthewriter** [comment]
Something like "For centuries we've learned that if you want to give something to someone you first have to take it from someone else. Life is a zero-sum-game. So why give? Why share? But when a few kids get caught in a cave in Thailand, international helpers arrive within hours, when an earthquake shatters whole cities or floods drown entire regions and threaten hundred thousands, aides from all over the world rush in for rescue - without asking for anything, just helping, just cooperating. That's what people do. All over the world. Why? What's in it for them?"

**Comment by Marcthewriter** [comment]
Or quote Adam Smith? And add a bit?

"How selfish soever man may be supposed, there are evidently some principles in his nature, which interest him in the fortunes of others, and render their happiness necessary to him, though he derives nothing from it, except the pleasure of seeing it."
Adam Smith, The Theory of Moral Sentiment (1759)
And if man derived more from it than just the "pleasure of seeing it."? Because those "principles in his nature" actually are general principles of nature? 
Here is the story of this general principle: the cooperation benefit.

**Comment by SeloSlav** [comment]
@Marcthewriter I tried looking through old PDFs of the text but I can't find what I'm looking for. Let me know you have something or whether we should just skip it. Cheers.

**Comment by ole-peters** [comment]
I don't remember this. I wrote something?
I generally think it's a good structure to 
* tell people what you'll tell them
* tell them
* tell them what you've just told them.
But we don't follow that structure in this case, and there's also something quite amusing about starting with "This is farmer Bill."
I like that nice starting slide "Farmers Fable - a tale about cooperation"

So on the whole: happy to leave it as it is.

I would make is "Farmers Fable" (not Farmer's Fable)

**Comment by Marcthewriter** [comment]
I am with Ole on Farmers Fable.

What about increasing suspense and attention getting a bit by slightly adjusting "A tale about cooperation" (though I like it's humble coolness) with somethink like I mentioned already?

Farmers fable
The secret of cooperation

Farmers fable
The secret benefit of cooperation

Farmers fable
The unknown benefit of cooperation

Farmers fable
Shifting paradigm: The unknown benefit of cooperation

**Comment by davidsarac** [comment]
Great!

If all are happy, let us proceed.

Cheers!

**Comment by ole-peters** [comment]
I like the understated "A tale of cooperation"
But don't let that stop you -- I tend to understate things, and then no one knows what's interesting about it.

**Comment by Marcthewriter** [comment]
Though having worked in advertising for decades (or because of it?) I too like 

> the understated "A tale of cooperation"
>
Just the former advertiser in me thinks about peacocking ... let's go with the understatement :-)

**Comment by SeloSlav** [comment]
Sounds good! So I take it we leave it as is, change to "Farmers Fable", with subtitle "A tale of cooperation"?

**Comment by Marcthewriter** [comment]
Yes
