### ISSUE TITLE
twitter handles

### ISSUE THREAD

**Issue by ole-peters** [SeloSlav/FarmersFable#2]
We do a lot of advocacy work for this project on twitter. Let's make sure people have access to our twitter handles/profiles. For example, we could do this in the acknowledgments - link to everyone's twitter account. 

Maybe also on that cool slide of the team all together (plus the cat).

**Comment by SeloSlav** [comment]
The last slide is fun but it's quite cluttered. The only way I can think of displaying these is as Twitter buttons that link to our pages when clicked.

![image](https://user-images.githubusercontent.com/8828948/57027838-57c07880-6bf2-11e9-99ee-11c728654232.png)

Perhaps better linked by our names in the credits page?

![image](https://user-images.githubusercontent.com/8828948/57027904-7f174580-6bf2-11e9-97f2-78f4b7d54443.png)

Let me know what you like better.

**Comment by ole-peters** [comment]
Have you tried without the icons? Especially the blue color breaks the style a bit. Maybe just the twitter handle as a link on the final slide (if that looks ok). 

On the credits page: similar, I wouldn't put the twitter icon there, not even the handle, just maybe make the names link to the twitter profiles. If we have the handle, like @ole_b_peters, visible on the final page, then it's ok if it's not visible on the credits page.

**Comment by SeloSlav** [comment]
We could use these icons instead:

![image](https://user-images.githubusercontent.com/8828948/57035907-f60b0900-6c07-11e9-9e8d-31de771934a6.png)

I suppose it's mostly assumed that prepending @ means we'll be linking to Twitter in any case.

**Comment by Marcthewriter** [comment]
or this one

![icons8-twitter-26](https://user-images.githubusercontent.com/50121811/57037276-07c7cd00-6c57-11e9-80c6-bcf7dabb67d3.png)

**Comment by Marcthewriter** [comment]
or this one which would correspond with the black arrow-buttons
![43-twitter-512](https://user-images.githubusercontent.com/50121811/57037472-93415e00-6c57-11e9-9cc2-534f3bddd6c8.png)

**Comment by SeloSlav** [comment]
> 
> 
> or this one which would correspond with the black arrow-buttons
> ![43-twitter-512](https://user-images.githubusercontent.com/50121811/57037472-93415e00-6c57-11e9-9cc2-534f3bddd6c8.png)

Good catch! Let's use this one?

**Comment by SeloSlav** [comment]
Looks like this btw:

![image](https://user-images.githubusercontent.com/8828948/57037781-f1951f00-6c0c-11e9-9f22-641c9a69ca8c.png)

**Comment by Marcthewriter** [comment]
I think, if

- we use both slides (picture/credits) we don't need names on the group picture, and probably one of your out-lined icons looks nicer - set in one line like the upper one withe the blue icons

- we use just the credits I'd just link to twitter or homepages, due to individual preferences

So the question still is: credits and/or group picture? For me credits would be sufficent (even without the Marc-illustration) but both slides also would be okay

**Comment by SeloSlav** [comment]
I wouldn't mind seeing them on both. On credits page we can have both twitter icon and custom url (for  websites).

Not sure most people will know who is who based on the illustration so the names and icons would help on the teams page.

**Comment by Marcthewriter** [comment]
> Not sure most people will know who is who based on the illustration so the names and icons would help on the teams page. <

Got a point there ^^

**Comment by SeloSlav** [comment]
Inverted the black and white here. Looks a lot cleaner.

![image](https://user-images.githubusercontent.com/8828948/57124616-49ca3f00-6d3b-11e9-9108-e18ec196ba28.png)
