### ISSUE TITLE
keep trajectories displayed when comparing to (non)cooperation

### ISSUE THREAD

**Issue by ole-peters** [SeloSlav/FarmersFable#3]
Sequence:

1) Bill's trajectory (non-coop) -> keep this fixed and displayed.
2) Ann's trajectory (non-coop) -> generate this while also displaying Bill's as fixed.
Then keep both fixed and displayed.
3) Cooperation -> generate the cooperative trajectory that corresponds to the previously generated trajectories of Bill and Ann. No new random numbers are needed.
4) This actually removes the need for the 4th step (which is to show what Bill and Ann would have experienced had they not cooperated - we already know this).
5) [or new 4)] continue the trajectories.
Keep the trajectories displayed up the point we already know them, i.e. 100, and then just keep going to a large number of harvest where the fluctuations become clearly irrelevant (maybe visible, but clearly unimportant - not sure when that happens 10,000?).

**Comment by SeloSlav** [comment]
I see what you mean now about not generating new random trajectories.

Part 2 of chart 4 (cooperative case up to large n ticks) does actually continue the trajectory from the previous slide but now that I look at it this wouldn't be obvious to a viewer.

The reason it doesn't appears this way is that the chart is reset at 0 harvests on the axis. What I can do instead is merge those two slides and have the "next" button continue the trajectory.

I had this done at one point but for some reason opted to chunk up into two slides.

As for Bill and Ann's trajectories, do you mean to draw these completely on tick 1 and just have the cooperative case drawn in real time?

**Comment by ole-peters** [comment]
a) yes, that's what I meant -- 'have the "next button" continue the trajectory after 100 ticks' as you put it.

b) Bill and Ann's trajectories: I would 
+ draw Bill's in real time.
+ then leave that displayed and draw Ann's in real time over Bill's
+ then leave both displayed and draw the cooperation in real time over both
+ then extend all three to the long time (10,000 or whatever make sense).

Maybe this isn't good for some reason, but I think it's just a simplification of what we have. 
At the moment we 
+ draw Bill's, 
+ then a new one for Bill and one for Ann, 
+ then Bill and Ann cooperating (this may be based on new individual harvests, I don't know)
+ then a new one for Bill, a new one for Ann, and the cooperating trajectory
+ then the long trajectory.

**Comment by SeloSlav** [comment]
I see what you mean. This can be done quite easily actually. I just need to execute the update functions in steps instead of in parallel.

**Comment by SeloSlav** [comment]
I was little over optimistic here. Looked into this again and this is actually too complicated for the current scope. Looks like there are limitations with the charting library which prevent drawing series one after another. This can be reexamined if possible by someone else once I hand over the source code.
