### ISSUE TITLE
Refactor Detailed Computation

### ISSUE THREAD

**Issue by SeloSlav** [SeloSlav/FarmersFable#30]
Opened an issue here to streamline communication.

I've uploaded a preliminary refactoring of the page.

What's missing:

* Animation for pooling/sharing (like simple demonstration)
* ~~New graphics for sun and rain, i.e. x1, x3~~

Let me know if it's moving in the right direction...

**Comment by Marcthewriter** [comment]
Looks good. Some clicks are missing at later stage of cooperation but I guess that’s just for now

**Comment by Marcthewriter** [comment]
At the coop-step “Bill again triples his wheat to 6.” we should make it even more clear: “Bill again triples his wheat, this time to 6.”
What do you think?

**Comment by Marcthewriter** [comment]
And at the almost last step we might also insert the numbers:

they pool again, which makes 8 bundles./
Sie legen wieder zusammen. Das ergibt 8.

Click

Pooling animation

Click

And share again.  /
Und teilen erneut. 

Click

Sharing animation

Click

To end up with 4 bundles each...

I think than we could skip those numbers on the left hand side of the Ann and Bill illustrations.

**Comment by SeloSlav** [comment]
>  later stage

I actualyl don't know what you're referring to. Could you be specific?

**Comment by SeloSlav** [comment]
> 
> 
> At the coop-step “Bill again triples his wheat to 6.” we should make it even more clear: “Bill again triples his wheat, this time to 6.”
> What do you think?

Done.

**Comment by SeloSlav** [comment]
> 
> 
> And at the almost last step we might also insert the numbers:
> 
> they pool again, which makes 8 bundles./
> Sie legen wieder zusammen. Das ergibt 8.
> 
> Click
> 
> Pooling animation
> 
> Click
> 
> And share again. /
> Und teilen erneut.
> 
> Click
> 
> Sharing animation
> 
> Click
> 
> To end up with 4 bundles each...
> 
> I think than we could skip those numbers on the left hand side of the Ann and Bill illustrations.

I made the changes. Can you check again?

**Comment by Marcthewriter** [comment]
Looks good. Only at “Bill again triples his wheat, this time to 6.” it looks to me as everything appears with one click - text and animations. 

So there should be second click after the text to get the illustrations. 

And should we split the last step into two?

Click

To end up with 4 bundles each/
Nun haben beide je 4 Bündel

Click

Share

Click
Add to the above text:

- one more each than without pooling and sharing./
- je eines mehr als sie ohne Zusammenlegen und Teilen haben. 

Click. 

Red circles.

**Comment by Marcthewriter** [comment]
In the German translation there are minor mistakes. I mark the necessary changes fat (or comment):

No comma in this sentence and:
Mit der ersten Ernte verdreifach**t** sie ihr Getreide.

![Bildschirmfoto 2019-06-03 um 03 49 27](https://user-images.githubusercontent.com/50121811/58771162-fdc91f00-85b2-11e9-8f7f-5b8bd3a7d363.png)


Bill verdreifacht sein Getreide, jetzt **zu** 6.

![Bildschirmfoto 2019-06-03 um 03 50 17](https://user-images.githubusercontent.com/50121811/58771167-015ca600-85b3-11e9-96a1-25a953dd8048.png)

**Comment by Marcthewriter** [comment]
On those slides some underlying graphic seems to be not covered entirely?

![Bildschirmfoto 2019-06-03 um 03 48 10](https://user-images.githubusercontent.com/50121811/58772487-83e86400-85b9-11e9-9b2b-9e313d7ac8c3.png)
![Bildschirmfoto 2019-06-03 um 03 48 19](https://user-images.githubusercontent.com/50121811/58772488-83e86400-85b9-11e9-89ec-85f09d0b29d9.png)
![Bildschirmfoto 2019-06-03 um 03 48 30](https://user-images.githubusercontent.com/50121811/58772489-83e86400-85b9-11e9-8d84-38518bed78b5.png)
![Bildschirmfoto 2019-06-03 um 03 48 40](https://user-images.githubusercontent.com/50121811/58772490-8480fa80-85b9-11e9-8ab9-140a5d9f0b30.png)

**Comment by SeloSlav** [comment]
Okay I believe I have completed all the additional fixes. Can you confirm that all the text/clicks are now 100% complete?

I can not make any additional changes after I have begun the pooling/sharing animations without doing everything from scratch.

**Comment by SeloSlav** [comment]
I went through all the text again and fixed a few slides in the middle where the text/clicks were not separated. I think it looks good now. Let me know.

**Comment by Marcthewriter** [comment]
Looks good, only three things:

1. At the beginning of the cooperation part there is:

**After the first harvest, Ann has 3 and Bill has 1.**/
Nach der ersten Ernte hat Ann 3 und Bill hat 1.
Click
**They pool...**/
Sie legen zusammen...
Click
Animation
Click
**...and share...**/
...und teilen...
Click
**...and both have 2.**/
nun haben beide 2.
Animation

It should be

**After the first harvest, Ann has 3 and Bill has 1.**/
Nach der ersten Ernte hat Ann 3 und Bill hat 1.
Click
**They pool...**/
Sie legen zusammen...
Click
Animation
Click
**...and share and both have 2.**/
...und teilen. Nun haben beide 2.
Click
Animation

So, the text "...and share and both have 2."/"...und teilen, nun haben beide 2." is finished after one click and the animation follows. 
So basically you just have to shift the text **...and both have 2.**/...Nun haben beide 2." to the the half-sentence before and make it one sentence.


2. At the end of the cooperation part there is 

**They pool again, which makes 8 bundles.**/
Sie legen wieder zusammen. Das ergibt 8.
Click
Animation
Click
**And share again.**/
Und teilen erneut.
Click
**To end up with 4 bundles each.**/
Nun haben beide je 4 Bündel.
Click
Animation
**One more each than without pooling and sharing.**/
Je eines mehr, als sie ohne Zusammenlegen und Teilen haben.
Click
Animation (Red Circles).

There is one Click too much between 

**And share again.**/
Und teilen erneut.
Click
**To end up with 4 bundles each.**/
Nun haben beide je 4 Bündel.

It should be

**They pool again, which makes 8 bundles.**/
Sie legen wieder zusammen. Das ergibt 8.
Click
Animation
Click
**And share again - to end up with 4 bundles each.**/
Und teilen erneut. Nun haben beide je 4 Bündel. 
Click
Animation
**One more each than without pooling and sharing.**/
Je eines mehr, als sie ohne Zusammenlegen und Teilen haben.
Click
Animation (Red Circles).


3. Sun and Cloud still look very pixled to me. I think we had this issue at some of the earlier slides as well.

**Comment by SeloSlav** [comment]
Okay I've addressed the above concerns. The text/clicks should all be fixed now (and hopefully sun/cloud image resolutions).

**Comment by Marcthewriter** [comment]
Sun/cloud resolution is good now.

With the clicks: only at the last one, there is one click missing (the bold one below). Sorry, I forgot it in the script!

**They pool again, which makes 8 bundles.**/
Sie legen wieder zusammen. Das ergibt 8.
Click
Animation
Click
**And share again - to end up with 4 bundles each.**/
Und teilen erneut. Nun haben beide je 4 Bündel.
Click
Animation
**Click**
**One more each than without pooling and sharing.**/
Je eines mehr, als sie ohne Zusammenlegen und Teilen haben.
Click
Animation (Red Circles).

**Comment by Marcthewriter** [comment]
And there are to issues in the German translation:

![Bildschirmfoto 2019-06-03 um 23 39 09](https://user-images.githubusercontent.com/50121811/58836412-0f650200-8659-11e9-947d-ffacebe9a709.png)

Here the text should be
"Mit der ersten Ernte verdreifach**t** sie ihr Getreide."

(no comma, "t" instead of "en" at the end of "verdreifacht" - actually it is the sentence which currently is used (wrongly) in the issue below.

***
Here instead of 
"Mit der ersten Ernte verdreifacht sie ihr Getreide."
it needs to be
"Mit der **zweiten** Ernte verdreifacht **er sein** Getreide."

![Bildschirmfoto 2019-06-03 um 23 39 25](https://user-images.githubusercontent.com/50121811/58836546-610d8c80-8659-11e9-9d42-973a5e774a4f.png)

**Comment by SeloSlav** [comment]
> **One more each than without pooling and sharing.**/

I'm not sure I understand what you mean by this.

Fixed the German translations above.

**Comment by Marcthewriter** [comment]
What I mean is:

**They pool again, which makes 8 bundles.**/
Sie legen wieder zusammen. Das ergibt 8.

Click

Animation: Pooling to 8

Click

**And share again - to end up with 4 bundles each**./
Und teilen erneut. Nun haben beide je 4 Bündel.

Click

Animation: sharing to 4 each

**> CLICK < This Click is missing**

**One more each than without pooling and sharing.**/
Je eines mehr, als sie ohne Zusammenlegen und Teilen haben.
**(REMARK: In the German translation the comma after the third word is missing)**

Click

Animation (Red Circles).

**Comment by Marcthewriter** [comment]
Sorry, had to correct the above post

**Comment by Marcthewriter** [comment]
Once the above issues have been implemented, you can make the pooling-sharing animations, I can adapt the movies, and send you the new links, and we are done :-)

**Comment by SeloSlav** [comment]
@Marcthewriter Is there any way we can skip the animations? From an end user perspective it's very clear what's happening.

**Comment by SeloSlav** [comment]
> 
> 
> What I mean is:
> 
> **They pool again, which makes 8 bundles.**/
> Sie legen wieder zusammen. Das ergibt 8.
> 
> Click
> 
> Animation: Pooling to 8
> 
> Click
> 
> **And share again - to end up with 4 bundles each**./
> Und teilen erneut. Nun haben beide je 4 Bündel.
> 
> Click
> 
> Animation: sharing to 4 each
> 
> **> CLICK < This Click is missing**
> 
> **One more each than without pooling and sharing.**/
> Je eines mehr, als sie ohne Zusammenlegen und Teilen haben.
> **(REMARK: In the German translation the comma after the third word is missing)**
> 
> Click
> 
> Animation (Red Circles).

Have you cleared cache recently? I feel as though I've implemented this. Otherwise, it's still not clear to me what you're suggesting.

**Comment by Marcthewriter** [comment]
> > What I mean is:
> > **They pool again, which makes 8 bundles.**/
> > Sie legen wieder zusammen. Das ergibt 8.
> > Click
> > Animation: Pooling to 8
> > Click
> > **And share again - to end up with 4 bundles each**./
> > Und teilen erneut. Nun haben beide je 4 Bündel.
> > Click
> > Animation: sharing to 4 each
> > **> CLICK < This Click is missing**
> > **One more each than without pooling and sharing.**/
> > Je eines mehr, als sie ohne Zusammenlegen und Teilen haben.
> > **(REMARK: In the German translation the comma after the third word is missing)**
> > Click
> > Animation (Red Circles).
> 
> Have you cleared cache recently? I feel as though I've implemented this. Otherwise, it's still not clear to me what you're suggesting.

Okay, I see

**Comment by Marcthewriter** [comment]
> @Marcthewriter Is there any way we can skip the animations? From an end user perspective it's very clear what's happening.

I'd love to have it, but if it is such an anoying task ...?

**Comment by Marcthewriter** [comment]
> @Marcthewriter Is there any way we can skip the animations? From an end user perspective it's very clear what's happening.

So, if it is doable within the planned hours I'd appreciate having it, if not or if you really hate it so much, leave it. Just let me know, so I know when to adapt the videos.

**Comment by SeloSlav** [comment]
> 
> 
> > @Marcthewriter Is there any way we can skip the animations? From an end user perspective it's very clear what's happening.
> 
> So, if it is doable within the planned hours I'd appreciate having it, if not or if you really hate it so much, leave it. Just let me know, so I know when to adapt the videos.

I'm currently at 11 hours. It will be doable within 20 hours (I'm estimating around 5-10 more from where I'm at currently), but I probably won't be able to deliver the update until sometime around the end of next week at this stage.

**Comment by Marcthewriter** [comment]
Well, then we'll leave it as it is.

**Comment by SeloSlav** [comment]
I take it we are done here now?
