### ISSUE TITLE
Tablet Support

### ISSUE THREAD

**Issue by SeloSlav** [SeloSlav/FarmersFable#31]
Let's list the devices where clicking is not working here...

**Comment by Marcthewriter** [comment]
I just could test on my devices:
iPhone 6s
iPad Air

**Comment by SeloSlav** [comment]
Unfortunately I've discovered that Construct 2 does not (fully) support newer device types, such as the ones you've mentioned. I have done some research and to the very best of my knowledge I do not believe there is a solution to address clicks that do not register at the moment. 

https://www.construct.net/en/tutorials/making-an-ios-web-app-with-construct-2-53

**Comment by SeloSlav** [comment]
I spent four hours researching this with no solution. I don't think it will be affordable to address this even if there is a solution, which I highly doubt. One of the realities of web development is that you often have to pick and choose which platforms will best suited for the project. In the interest of time I have to close this issue now.

**Comment by Marcthewriter** [comment]
This is a nightmare!

**Comment by SeloSlav** [comment]
Understandable. However, at the very beginning of this project we did specify this would be a desktop-only experience. Lots of research needs to go into feature planning ahead of time. So we can't just keep adding features under the assumption they will all just work.

**Comment by Marcthewriter** [comment]
If I follow this link

![Bildschirmfoto 2019-06-03 um 23 27 41](https://user-images.githubusercontent.com/50121811/58835888-784b7a80-8657-11e9-8553-48cedce041b7.png)

which says something about iPhone 6s, I get there

https://www.scirra.com/manual/119/touch

I guess you've been there already, too ...

**Comment by SeloSlav** [comment]
Yes I've seen that page. It mentions iPhone6 but not 6S. My conclusion at this stage is that it will simply not be possible to address fixes for every single device type. This is a problem that resides with the Construct platform and will either resolve itself or not on its own with time. I also personally don't have the time to investigate this further. It seems like a dead end.

**Comment by Marcthewriter** [comment]
I hate it, but for the time being ...
