### ISSUE TITLE
kilo, kilos, kg

### ISSUE THREAD

**Issue by ole-peters** [SeloSlav/FarmersFable#32]
Early on you use kg to refer to kilos, which I think is good. Later it's kilo and kilos, and in one instance, it's singular kilo though it should be plural kilos ("for each 100 kilo he sows").

Suggestion: just use kg throughout.

**Comment by Marcthewriter** [comment]
Ok, then let's unify this and then we're done:

"Here is what would happen to **1 kg** of seeds,..."/
"Das würde aus **1 kg** Saat über ..."

![Bildschirmfoto 2019-06-06 um 00 47 06](https://user-images.githubusercontent.com/50121811/58995547-fb560780-87f4-11e9-8684-d3f1c07138e6.png)

"In a bad season, Bill only harvests **70 kg** of seeds for each **100 kg** he sows. ..."/
"In einer schlechten Saison erntet Bill nur **70 kg** Getreide je **gesähter 100 kg** ."

![Bildschirmfoto 2019-06-06 um 00 47 37](https://user-images.githubusercontent.com/50121811/58995563-001abb80-87f5-11e9-959c-66fc68ca37e9.png)

**Comment by SeloSlav** [comment]
> 
> 
> Ok, then let's unify this and then we're done:
> 
> "Here is what would happen to **1 kg** of seeds,..."/
> "Das würde aus **1 kg** Saat über ..."
> 
> ![Bildschirmfoto 2019-06-06 um 00 47 06](https://user-images.githubusercontent.com/50121811/58995547-fb560780-87f4-11e9-8684-d3f1c07138e6.png)
> 
> "In a bad season, Bill only harvests **70 kg** of seeds for each **100 kg** he sows. ..."/
> "In einer schlechten Saison erntet Bill nur **70 kg** Getreide je **gesähter 100 kg** ."
> 
> ![Bildschirmfoto 2019-06-06 um 00 47 37](https://user-images.githubusercontent.com/50121811/58995563-001abb80-87f5-11e9-959c-66fc68ca37e9.png)

Okay I've updated this.

**Comment by Marcthewriter** [comment]
Hm, I cleared my cache several times and still can't see the changes. 
And suddenly in the German version all the umlauts are gone.
