### ISSUE TITLE
credits, umlauts

### ISSUE THREAD

**Issue by ole-peters** [SeloSlav/FarmersFable#33]
The credits look strange now - 
![Untitled](https://user-images.githubusercontent.com/20874346/59015384-c2d71d80-8836-11e9-81dd-8a816f2792a9.png)

Also, the final cartoon with everyone is visible again.

A user on twitter said the link to the LML or researchers.one wasn't working. I think it is actually working, but it doesn't open a new tab. It's probably best for any clicked link to open a new tab or even window.

**Comment by Marcthewriter** [comment]
And in the German version suddenly all umlauts seem to be gone ...?
LML link: opened in a new tab here...

**Comment by ole-peters** [comment]
I think what happens with the links is this. The first time you click on a
link, a new tab opens. When you click on a link after that, no new tab
opens - instead, whatever is in the previously newly opened tab changes to
what's linked.

This is easily missed because it happens in the background.

**Comment by Marcthewriter** [comment]
Also the explanation of the principle looks strange and is again starting with 4. Looks like some earlier version has been  uploaded ...

![Bildschirmfoto 2019-06-06 um 09 55 09](https://user-images.githubusercontent.com/50121811/59016394-6af1e400-8841-11e9-9fa2-74149ade06bf.png)

**Comment by SeloSlav** [comment]
I'm not sure why an older version was uploaded. That was strange. It's reverted now.

**Comment by Marcthewriter** [comment]
I see. Looks better now :-)
