### ISSUE TITLE
for long trajectories, speed up by displaying only every X steps

### ISSUE THREAD

**Issue by ole-peters** [SeloSlav/FarmersFable#4]
If trajectories take too long to generate on screen, I suspect the bottleneck is the display code, not the generation of random numbers or computation of the values along the trajectories. 

So maybe this works: generate the full trajectories, and display in chunks of 10 or 100 or 1000 steps. The chunkiness can increase with time to give a speeding-up effect.

**Comment by SeloSlav** [comment]
I've updated the library to the latest version and implemented the proper stepSize parameter but it's still not working.

I've tried everything available in the documentation so I don't think this is doable any time soon unfortunately.

Any other ideas for getting the message across on the long trajectory? I think 1000 ticks is about the max in terms of draw speed and attention span.

**Comment by SeloSlav** [comment]
I looked into this some more and can confirm that skipping values is not actually a feature that has been developed for this library.

You can only skip the tick "labels" on the x and y axes, but each value in the series must be drawn sequentially.

The only thing I can recommend is making the max value for the final chart between 500 and 1000, which is when the collaboration benefit becomes clear.

**Comment by ole-peters** [comment]
We could delete the x labels and just compute the value every 10 or 50 or 100 steps [...].

Let's say you compute what the values are at steps 100, 110, and 120, is it not possible to just pass on those values to be graphed?
You'd just pass a sequence of numbers to be drawn, like 102392, 192834, 298237. If it's not possible to associate it with the right x values, we could leave out the x labels.

I assume it's impossible to pass a 2-d array like
100, 102392
110, 192834
120, 298237

My idea was to pass a sequence of x-values like this, to achieve the appearance of a speed-up:
1
2
3
..
10
20
..
100
200
..
1000
2000
..
10,000

**Comment by SeloSlav** [comment]
We could compute the first time by feeding the chart update function an
array of all those values which we predefine. But then subsequent resets
won't follow any random trajectory.

**Comment by ole-peters** [comment]
Is it not possible to compute a new array for the next update? 

I would fix the first one (or not even that -- if the trajectory is long enough the result is certain), and then just re-compute the array, and pass it on to the plotting function.

[I'm making this up, I've never used the language; I'm just hoping that that's possible.]

**Comment by SeloSlav** [comment]
```
My idea was to pass a sequence of x-values like this, to achieve the appearance of a speed-up:
1
2
3
..
10
20
..
100
200
..
1000
2000
..
10,000
```

This isn't possible with this library. Unfortunately I picked a very high level library to start out and I did not anticipate some of these more complicated requirements. It forces you to update the chart every x tick, and you can't skip them.

I looked into the stepSize param a little more and it only applies to when to display you are allowed to display new labels.

**Comment by SeloSlav** [comment]
@ole-peters What if there was another slide after the 500-1000 tick slide, showing a static chart with at 10,000 ticks?

The bottleneck seems to be Construct 2 because the way it interacts with the charting library is that it requires the x axis to be updated in units of 1 every tick.

I just don't think I can get around this in any reasonable time frame myself.
