### ISSUE TITLE
ordering of slides

### ISSUE THREAD

**Issue by Marcthewriter** [SeloSlav/FarmersFable#7]
Since we want to have an agreement on the ordering of slides by Friday May 3:

I think the order is settled so far.

Only question remains: how and where to insert/offer the principle's explanation?

Option 1: 
After slide "Now imagine Bill and Ann get married ..." start principle's explanation, after explanation continue to graph of cooperation

Option 2: 
On slide "Now imagine Bill and Ann get married ..." offer optional link to explanation

Option 3: 
After slide "Anything that grows multiplicativy ..."

Option 4 (as of now): 
On slide "Anything that grows multiplicativy ..." offer optional link to explanation

I am fine with all of them.

Only point I think: if we do options 3 or 4, we should on slide "Now imagine Bill and Ann get married ..." re-establish the simple pool/share-animation we had already at an earlier stage

**Comment by ole-peters** [comment]
I vote for Option 3 - without going into the optional computation, the story feels a little bit short.

And agreed on the final point: we definitely need the simple animation of what we mean by pooling and sharing, after "Now imagine.."

BTW: if the marriage thing feels weird, we can drop it and just say "Now imagine that Bill and Ann make a pact..."
We don't have to explain their reasons for making this pact, as long as we're clear about what they're doing.

**Comment by SeloSlav** [comment]
I also agree that without a little something extra (link, explanation) at "Now imagine Bill and Ann get married..." then the pooling and sharing mechanism that follows just seems like magic.

My vote would be keep everything as is, but adding a "quick intro" to the mechanism after "Now imagine Bill and Ann get married ...". For example, the simple animation that existed before.

**Comment by Marcthewriter** [comment]
> My vote would be keep everything as is, but adding a "quick intro" to the pool/sharing protocol after "Now imagine Bill and Ann get married ...". by reintroducing the simple animation that existed before. < 

Yes, I think this is what Ole and I had in mind

> BTW: if the marriage thing feels weird, we can drop it and just say "Now imagine that Bill and Ann make a pact..."
> We don't have to explain their reasons for making this pact, as long as we're clear about what they're doing.

Either that - or on the next slide instead of 
"As the years go by, they both feel getting married was a good idea. Life got better."

we could write

"As the years go by, they both feel **pooling and sharing** was a good idea. Life got better."

But I have more (small) text issues so I'd say we open a seperate issue on text

**Comment by SeloSlav** [comment]
I added a quick animation demonstrating pooling and sharing at the third collaboration slide:

![image](https://user-images.githubusercontent.com/8828948/57129635-df6dca80-6d4b-11e9-9535-de474c034ccf.png)

**Comment by ole-peters** [comment]
Can we have that animation without the static pile of grains in the middle?

**Comment by SeloSlav** [comment]
Sure. I removed it.

**Comment by Marcthewriter** [comment]
As I see it currently now they pool the bundles like: Ann's two and Bill's four become ONE bundle in the middle. Then from this one bundle three emerge to each side. I guess it should be two and four being pooled to SIX bundles in the middle? Which then seperate to three on each side?

**Comment by SeloSlav** [comment]
I agree. There should be a pause where 6 are displayed, then they are separated afterwards.

**Comment by SeloSlav** [comment]
Hpw does it look now?

**Comment by Marcthewriter** [comment]
I think Ann's 2 and Bill's 4 bundles should not merge into one bundle in the first place. They just move between the two characters next to each other so there are 6 bundles. The they are seperated again, 3 on each sid.

**Comment by SeloSlav** [comment]
Sounds good. Will have to rework this a bit then. I took some short cuts with "grouping". Will revert back to this issue tomorrow.

**Comment by SeloSlav** [comment]
That sounds like the best way to do it! Thanks

**Comment by SeloSlav** [comment]
Let me know if there are any remaining issues but this issue seems closed to me.
