### ISSUE TITLE
text changes

### ISSUE THREAD

**Issue by SeloSlav** [SeloSlav/FarmersFable#8]
@Marcthewriter can add his recommended changes here.

**Comment by Marcthewriter** [comment]
So here would be several minor suggestions about the wording on several slides. _Italics_ just mark the changed words. Doesn't mean it should be set in _italics_. Or mark remarks.



![Bildschirmfoto 2019-04-28 um 11 48 01](https://user-images.githubusercontent.com/50121811/57038706-db15b480-6c5a-11e9-88c7-3a70d63112fd.png)

It’s about another unintuitive a _fascinating_ thing that happens in exponential growth. To see this, we need to be a little more realistic, and introduce bad seasons.

(Other suggestions but „fascinating“? I’d like to phrase this more involving than „unintuetively“))



![Bildschirmfoto 2019-04-28 um 11 49 51](https://user-images.githubusercontent.com/50121811/57038781-0c8e8000-6c5b-11e9-8dbd-3eb4554a8d56.png)

_Seperating sentences:_
Ann is also a farmer. She faces equally common good an bad years, too. But when this happens is independent of Bill’s harvests.

_(We even could delete the last sentence here. On the next chart - see below - we tell the same thing in different words - and show it. And on the next chart the content is phrased more clearly. If we do not delete it in the above chart, we should make it a seperate sentence. To keep sentences short)_



![Bildschirmfoto 2019-04-28 um 11 50 04](https://user-images.githubusercontent.com/50121811/57038863-43649600-6c5b-11e9-97fb-d7d4e59942ab.png)

_Same here with separating sentences:_

Ann and Bill have similar sized farms. But they don’t always face the same uncertainties at the same time.



![Bildschirmfoto 2019-04-28 um 11 50 25](https://user-images.githubusercontent.com/50121811/57038630-b02b6080-6c5a-11e9-9299-3e08df640c36.png)

As the years go by, they both feel _pooling and sharing_ was a good idea. Life got better.



![Bildschirmfoto 2019-04-28 um 11 50 59](https://user-images.githubusercontent.com/50121811/57038933-7b6bd900-6c5b-11e9-95c0-34cf3422dc68.png)

Should the captions for Bill (Sharing) and Ann (Sharing) better be one of the following?

Bill (Cooperating), Ann (Cooperating)

Bill (cooperate), Ann (cooperate)

Bill (Coop), Ann (Coop)

Bill (pool/share), Ann (pool/share)



![Bildschirmfoto 2019-04-28 um 11 51 27](https://user-images.githubusercontent.com/50121811/57038986-a48c6980-6c5b-11e9-88d8-ca278ef6f039.png)

_Seperating sentences again..._

„This is amazing“, realises Bill, „pooling and sharing not only reduces risk. It actually accelerates and increases growth - for everybody involved!

_(Would it be „pooling and sharing not only reduces risk. It actually …“ or "„pooling and sharing not only reduces risk. It They actually …“?)_



![Bildschirmfoto 2019-04-28 um 11 53 39](https://user-images.githubusercontent.com/50121811/57039004-ba9a2a00-6c5b-11e9-9e01-04b8c51cecb0.png)

_And finally - a different word for „_ignorance“?

_And: an alternative to_ „economics was developed too early“? 

Something like „When economics was developed it lacked crucial mathematical insight which only emerged much later.“

**Comment by Marcthewriter** [comment]
We also need a short note on the starting page telling that it does just work on desktop, laptop and pad(?) (yet). Not on mobile phones. 
Like “Currently for desktop, laptop, tablet”

**Comment by Marcthewriter** [comment]
Since there have been no comments on this I guess everything is aproved. 

There are just two answers missing: 

***
![Bildschirmfoto 2019-04-28 um 11 50 59](https://user-images.githubusercontent.com/50121811/57151278-c78c5a00-6dd0-11e9-988e-b4d3422b7252.png)

_Since we are talking about pooling and sharing I think the caption for_ Ann (Sharing) _and_ Bill (Sharing) _should rather be_ Ann (pool/share) _and_ Bill (pool/share)

_Any objections?_

***

![Bildschirmfoto 2019-04-28 um 11 53 39](https://user-images.githubusercontent.com/50121811/57151374-14703080-6dd1-11e9-82e2-7569bcbc7978.png)

_And here I'd write_ 

This insight shatters much of modern economic theory, which is unaware of this cooperation benefit.

The reasons for this are historical: 
When economics was developed it lacked crucial mathematical insight which only emerged much later.

_Any objections?_

**Comment by Marcthewriter** [comment]
Since we decided ro integrate the principle's explanation into the story and not jut offer it optionally (see Ole's comment from May 1 in issue "Ordering of slides" https://github.com/SeloSlav/FarmersFable/issues/7#issuecomment-488376169), we need to change the text on this slide:

![Bildschirmfoto 2019-05-04 um 03 45 01](https://user-images.githubusercontent.com/50121811/57172416-f67dec80-6e1f-11e9-8d56-087843717dc4.png)

The last sentence needs to be 
"Continue to learn more about the fundamental principle behind how pooling and sharing accelerate and increase growth."

Also klicking the right hand button now leads to continue with the explanation, and not directly to the last slide ("This inside ..."). The last slide follows after the explanation.

Ok?

**Comment by SeloSlav** [comment]
> 
> 
> Since we decided to integrate the principle's explanation into the story and not jut offer it optionally (see Ole's comment from May 1 in issue "Ordering of slides" [#7 (comment)](https://github.com/SeloSlav/FarmersFable/issues/7#issuecomment-488376169)), we need to change the text on this slide:
> 
> ![Bildschirmfoto 2019-05-04 um 03 45 01](https://user-images.githubusercontent.com/50121811/57172416-f67dec80-6e1f-11e9-8d56-087843717dc4.png)
> 
> The lower sentence needs to be
> "Continue to learn more about the fundamental principle behind how pooling and sharing accelerate and increase growth."
> 
> Also klicking the right hand button now leads to continue with the explanation, and not directly to the last slide ("This inside ..."). The last slide follows after the explanation.
> 
> Ok?

Done. Let me know how this sequences looks.

**Comment by Marcthewriter** [comment]
> > Since we decided to integrate the principle's explanation into the story and not jut offer it optionally (see Ole's comment from May 1 in issue "Ordering of slides" [#7 (comment)](https://github.com/SeloSlav/FarmersFable/issues/7#issuecomment-488376169)), we need to change the text on this slide:
> > ![Bildschirmfoto 2019-05-04 um 03 45 01](https://user-images.githubusercontent.com/50121811/57172416-f67dec80-6e1f-11e9-8d56-087843717dc4.png)
> > The lower sentence needs to be
> > "Continue to learn more about the fundamental principle behind how pooling and sharing accelerate and increase growth."
> > Also klicking the right hand button now leads to continue with the explanation, and not directly to the last slide ("This inside ..."). The last slide follows after the explanation.
> > Ok?
> 
> Done. Let me know how this sequences looks.

Ok for me. Ole? Others?

**Comment by Marcthewriter** [comment]
Actually, my English: Does the sentence need a comma?
""Continue, to learn more about the fundamental principle behind how pooling and sharing accelerate and increase growth."
or, like the initial version
"To learn more about the fundamental principle behind how pooling and sharing accelerate and increase growth, continue." (might be better)

**Comment by SeloSlav** [comment]
> 
> 
> We also need a short note on the starting page telling that it does just work on desktop, laptop and pad(?) (yet). Not on mobile phones.
> Like “Currently for desktop, laptop, tablet”

I will set a condition that if accessed by mobile will simply show text asking the user to try it on their desktop, laptop, or pad. How's that?

**Comment by SeloSlav** [comment]
> 
> 
> Actually, my English: Does the sentence need a comma?
> ""Continue, to learn more about the fundamental principle behind how pooling and sharing accelerate and increase growth."
> or, like the initial version
> "To learn more about the fundamental principle behind how pooling and sharing accelerate and increase growth, continue." (might be better)

I think the current implementation is the most proper English because continuing to learn about the mechanism is no longer optional.

**Comment by SeloSlav** [comment]
I pushed some text changes from all of the above for review. Let me know if I missed anything. As for the conclusion slide, "The reasons for this ignorance..." I like how it is set currently because of how confident and jarring it sounds.

Others?

**Comment by Marcthewriter** [comment]
> > We also need a short note on the starting page telling that it does just work on desktop, laptop and pad(?) (yet). Not on mobile phones.
> > Like “Currently for desktop, laptop, tablet”
> 
> I will set a condition that if accessed by mobile will simply show text asking the user to try it on their desktop, laptop, or pad. How's that?

Could do. Though I'd prefer a note to avoid dissapointing phone users just _after_ they expected and tried to use it.

**Comment by Marcthewriter** [comment]
> ...As for the conclusion slide, "The reasons for this ignorance..." I like how it is set currently because of how confident and jarring it sounds.
> 
> Others?

Might also be my English: does "ignorance" mean just "not knowing" or, like In German, "not wanting to know"? Which I would find too harsh and provoking rejection, turning people away instead of winning them.

**Comment by Marcthewriter** [comment]
> I pushed some text changes from all of the above for review. Let me know if I missed anything. As for the conclusion slide, "The reasons for this ignorance..." I like how it is set currently because of how confident and jarring it sounds.
> 
> Others?

Also: 
"economics was developed too early, ..." 
Economics was developed neither too early nor to late. It was developed when it was developed. A mistakes has been made (like in physics. Like in other sciences). Now it is being corrected. We won't win economists over by vilifing their profession (and them).

**Comment by bermanjoe** [comment]
I agree that "economics was developed too early, ..." is a bit too harsh,
but I can't see the corrections. Where are they displayed?


Yonatan

**Comment by Marcthewriter** [comment]
They are further up the thread

http://marcelsberg.com
http://www.facebook.com/MarcElsberg
http://www.twitter.com/Marc_Elsberg
http://www.instagram.com/marcelsberg

**Comment by Marcthewriter** [comment]
in the posting with the many slides

http://marcelsberg.com
http://www.facebook.com/MarcElsberg
http://www.twitter.com/Marc_Elsberg
http://www.instagram.com/marcelsberg

**Comment by Marcthewriter** [comment]
> I pushed some text changes from all of the above for review. Let me know if I missed anything. As for the conclusion slide, "The reasons for this ignorance..." I like how it is set currently because of how confident and jarring it sounds.
> 
I'd clean up this slide textwise, too - as mentioned above:

![Bildschirmfoto 2019-05-05 um 16 11 55](https://user-images.githubusercontent.com/50121811/57195242-9470d480-6f50-11e9-98fb-4d7350a8d4f2.png)

„This is amazing“, realises Bill. "Pooling and sharing not only reduces risk. It actually accelerates and increases growth - for everybody involved!"

Seperating sentences. No uppercasing of words. No parenthesis. Makes it clearer and easier to read.

Or even a shorter version (without Bill talking)? 

Pooling and sharing not only reduces risk. It actually accelerates and increases growth - for everybody involved!

**Comment by SeloSlav** [comment]
I uploaded some more changes. Let me know what's missing.

**Comment by Marcthewriter** [comment]
![Bildschirmfoto 2019-05-05 um 23 10 43](https://user-images.githubusercontent.com/50121811/57200347-1978df80-6f8b-11e9-94fc-33599e5000c9.png)

I'd still divide the sentences there _(italic)_:
„This is amazing“, realises Bill. "Pooling and sharing not only reduces _risk. It_ actually accelerates and increases growth - for everybody involved!"

**Comment by Marcthewriter** [comment]
The last slide (economics too early etc.) hasn't been decided on yet, I guess?

**Comment by Marcthewriter** [comment]
The pooling and sharing animation on this slide still needs a fix:

![Bildschirmfoto 2019-05-05 um 22 59 32](https://user-images.githubusercontent.com/50121811/57200373-796f8600-6f8b-11e9-8e91-fe7bab9f5b4e.png)

When pooling, the bundles need not collapse into one bundle like they currently do

![Bildschirmfoto 2019-05-05 um 23 06 02](https://user-images.githubusercontent.com/50121811/57200379-96a45480-6f8b-11e9-94f4-5abc4422d383.png)

but need to bee sortet side by side immediately to each other either like this 

![Coop](https://user-images.githubusercontent.com/50121811/57200393-c4899900-6f8b-11e9-8549-f989ea32a845.jpg)

or like this (currently)

![Bildschirmfoto 2019-05-05 um 23 05 14](https://user-images.githubusercontent.com/50121811/57200400-d79c6900-6f8b-11e9-80af-99d3cb55467b.png)

**Comment by Marcthewriter** [comment]
Ah, either changes aren't finished or there was a misunderstanding. We just need one version of 6 bundles in the middle. Currently there are two, as I see it. 
1. Ann's 2 and Bill's 4 bundles pool in a line of 6 between them. 
2. Then the pool re-orders in a jump to two lines of 3 bundles above each other. 
3. Those then seperate to both sides (Ann, Bill), 3 bundels each.

To keep things simple we can skip step 2. of the ones above. 
The line of 6 bundles between Ann and Bill seperates into two groups of 3 bundles to each side (Ann, Bill) (_without_ prior re-ordering into two liones of 3 bundles between Ann and Bill)

![Bildschirmfoto 2019-05-05 um 22 59 32](https://user-images.githubusercontent.com/50121811/57218308-48c43680-6ff5-11e9-814a-53dd8f78c49a.png)
***
![Bildschirmfoto 2019-05-06 um 11 36 48](https://user-images.githubusercontent.com/50121811/57218348-5f6a8d80-6ff5-11e9-9e26-d8c44b17052e.png)
***
![Bildschirmfoto 2019-05-05 um 22 59 41](https://user-images.githubusercontent.com/50121811/57218377-714c3080-6ff5-11e9-8acd-fdbb29473985.png)

**Comment by SeloSlav** [comment]
I fixed the above changes (initial pooling animation) and the sentence starting with "This is amazing..."

Could we get a consensus on the conclusion slide beginning with "This insight shatters much of..."

**Comment by Marcthewriter** [comment]
For the above mentioned reasons my choice still would be

"This insight shatters much of modern economic theory, which is unaware of this cooperation benefit.

The reasons for this are historical:
When economics was developed it lacked crucial mathematical insight which only emerged much later.

If you want ... "

Others?

**Comment by bermanjoe** [comment]
Perhaps instead of "When economics was developed":

When the foundations of economic theory were developed

**Comment by Marcthewriter** [comment]
okay with me ...

**Comment by SeloSlav** [comment]
Okay updated that last slide. Anything else that was missed?

**Comment by Marcthewriter** [comment]
> ![Bildschirmfoto 2019-05-05 um 23 10 43](https://user-images.githubusercontent.com/50121811/57200347-1978df80-6f8b-11e9-94fc-33599e5000c9.png)
> 
> Minor thing: I'd still divide the sentences there after "risk":
> „This is amazing“, realises Bill. "Pooling and sharing not only reduces risk. It actually accelerates and increases growth - for everybody involved!"

And doesn't this sentence come quite late in the sequence?

**Comment by Marcthewriter** [comment]
And there is still the pooling-sharing issue on this slide
(pool jumping from 6-in-1-row to 3-in-2-rows before shared amongst Ann and Bill)

> ![Bildschirmfoto 2019-05-06 um 11 36 48](https://user-images.githubusercontent.com/50121811/57218348-5f6a8d80-6ff5-11e9-9e26-d8c44b17052e.png)
>

**Comment by SeloSlav** [comment]
I updated the changes. Sometimes you need to clear your browser cache to see them in effect.

**Comment by Marcthewriter** [comment]
Yes, I can see it now
